## Importing packages

In [ ]:
import numpy as np
import pandas as pd

import random

from datetime import timedelta, time
from faker import Faker

import os

import ast

import json

## Initializing the parameters & defining the universe

In [751]:
BASE_DIR = os.path.abspath(os.path.join(os.getcwd(), "..", ".."))

In [752]:
fake = Faker('en_IN')
np.random.seed(42)

In [753]:
N_CUSTOMERS = 2000
N_ORDERS = 100000

In [754]:
# Defining the universe
cities = ["Bangalore", "Mumbai", "Delhi", "Chennai"]
veg_types = ["veg", "nonveg", "egg"]
cuisines = ["North Indian", "South Indian", "Biryani", "Italian", "Chinese", "Fast Food", "Healthy"]
courses = ["mains", "appetizers", "complements", "extras", "desserts & beverages"]
time_categories = ["late night", "breakfast", "lunch", "snack", "dinner"]

In [755]:
time_ranges = {
    "late night": (22, 2),
    "breakfast": (6, 10),
    "lunch": (11, 15),
    "snack": (16, 18),
    "dinner": (19, 22)
}

In [756]:
cuisine_items = {
    "North Indian Mains": [
        "Amritsari Kulcha", "Jeera Rice", "Veg Pulao", "Lachha Paratha", "Garlic Naan", "Plain Naan", 'Aloo Paratha', 
        "Gobhi Paratha", "Paneer Paratha", "Tandoori Roti", "Rumali Roti", "Chole Bhature", "Rajma Chawal"
    ],
    "North Indian Appetizers":[
        "Paneer Tikka", "Tandoori Chicken", "Hara Bhara Chicken Kabab", "Chicken Seekh Kabab", "Aloo Tikki", "Fish Amritsari",
        "Egg Bhurji", "Paneer Pakora", "Vegetable Pakora", "Chicken Pakora", "Egg Pakora"
    ],
    "North Indian Complements":[
        "Butter Chicken", "Paneer Butter Masala", "Dal Makhani", "Shahi Paneer", "Kadai Paneer", "Chicken Tikka Masala", 
        "Malai Kofta", "Chicken Curry", "Mutton Rogan Josh", "Palak Paneer", "Egg Curry", "Egg Masala", "Egg Bhurji Masala"
    ],
    "North Indian Extras":[
        "Boondi Raita", "Plain Curd", "Mint Chutney", "Onion Salad", "Green Salad",
        "Papad", "Masala Papad", "Pickle", "Butter", "Extra Gravy", "Boiled Egg"
    ],
    "North Indian Desserts & beverages":[
        "Gulab Jamun", "Rasgulla", "Rasmalai", "Kheer", "Rabri", "Lassi", "Chai", "Badam Milk"
    ],


    "South Indian Mains": [
        "Masala Dosa", "Plain Dosa", "Rava Dosa", "Onion Dosa", "Set Dosa", "Idli", "Vada", 
        "Upma", "Pongal", "Uttapam", "Paper Dosa", "Mysore Masala Dosa", "Appam", "Curd Rice", "Lemon Rice",
        "Bisibelebath", "Neer Dosa", "Kerala Parotta", "Egg Dosa", "Mini Tiffin", "Egg Uttapam", "Egg Parotta",
        "Chicken Dosa", "Chicken Uttapam", "Chicken Parotta"
    ],
    "South Indian Appetizers":[
        "Gobi 65", "Paneer 65", "Chicken 65", "Medu Vada", "Egg 65", "Egg Kalaki"
    ],
    "South Indian Complements":[
        "Sambar", "Curd", "Coconut Chutney", "Tomato Chutney", "Mint Chutney", "Spicy Onion Chutney", "Mushroom Curry", 
        "Chicken Curry", "Mutton Curry", "Egg Curry", "Chettinad Chicken Gravy", "Chettinad Egg Gravy"
    ],
    "South Indian Extras":[
        "Extra Sambar", "Extra Coconut Chutney", "Extra Tomato Chutney", "Gunpowder",
        "Medu Vada", "Samosa", "Masala Vada"
    ],
    "South Indian Desserts & beverages":[
        "Filter Coffee", "Buttermilk", "Rava Kesari", "Payasam", "Mysore Pak", "Coconut Ladoo", "Jaggery Ladoo"],


    "Biryani Mains": [
        "Chicken Biryani", "Mutton Biryani", "Veg Biryani", "Paneer Biryani", "Egg Biryani", "Egg 65 Biryani", 
        "Hyderabadi Chicken Biryani", "Lucknowi Chicken Biryani", "Kolkata Chicken Biryani" ,"Donne Mutton Biryani", 
        "Donne Chicken Biryani", "Boneless Chicken Biryani", "Prawn Biryani", "Fish Biryani", "Mushroom Biryani"
    ],
    "Biryani Appetizers":[
        "Chicken 65", "Paneer 65", "Mutton Chops", "Fish Fry", "Prawn Fry", "Chicken Tikka", "Tandoori Chicken", 
        "Paneer Tikka", "Chicken Seekh Kabab", "Hara Bhara Chicken Kabab", "Aloo Tikki", "Fish Amritsari", "Egg Bhurji",
        "Egg 65", "Egg Pakora", "Chicken Pakora"
    ],
    "Biryani Complements":[
        "Chettinad Chicken Curry", "Chettinad Mutton Curry", "Chettinad Egg Curry", "Chicken Curry", "Mutton Curry", "Egg Curry",
        "Paneer Butter Masala", "Dal Makhani", "Shahi Paneer", "Kadai Paneer", "Chicken Tikka Masala", "Malai Kofta",
        "Palak Paneer", "Egg Masala", "Egg Bhurji Masala"
    ],
    "Biryani Extras": [
        "Extra Masala", "Extra Gravy", "Boiled Egg", "Raita", "Green Salad", "Mint Chutney", "Onion Salad", 
        "Cucumber Salad", "Salan", "Mirchi Ka Salan"
    ],
    "Biryani Desserts & beverages":[
        "Gulab Jamun", "Rasgulla", "Rasmalai", "Kheer", "Rabri", "Lassi", "Chai", "Badam Milk"
    ],


    "Italian Mains": [
        "Margherita Pizza", "Chicken Farmhouse Pizza", "Chicken Pepperoni Pizza", "Veggie Supreme Pizza", "Paneer Pizza",
        "White Sauce Pasta (Chicken)", "White Sauce Pasta (Veg)", "Red Sauce Pasta (Chicken)", "Red Sauce Pasta (Veg)",
        "Lasagna Veg", "Lasagna Chicken", "Chicken Risotto", "Garlic Bread", "Cheese Garlic Bread"
    ],
    "Italian Appetizers": [
        "Garlic Bread", "Cheese Garlic Bread", "Bruschetta", "Stuffed Mushrooms", "Mozzarella Sticks", "Chicken Wings",
        "Boneless Chicken Bites", "Potato Wedges", "Poached Eggs", "Sunny Side Up Eggs", "CHicken Caesar Salad", "Veg Caesar Salad"
    ],
    "Italian Complements": [
        "Marinara Sauce", "Alfredo Sauce", "Pesto Sauce", "Arrabbiata Sauce", "Bolognese Sauce"
    ],
    "Italian Extras": [
        "Chilli Flakes", "Oregano", "Garlic Dip", "Cheese Dip", "Sour Cream Dip", "Marinara Dip",
        "French Fries", "Onion Rings", "Coleslaw"
    ],
    "Italian Desserts & beverages": [
        "Tiramisu", "Choco Lava Cake", "Panna Cotta", "Gelato", "Affogato", "Espresso", "Cappuccino", "Latte"
    ],


    "Chinese Mains": [
        "Veg Fried Rice", "Chicken Fried Rice", "Egg Fried Rice", "Schezwan Veg Fried Rice", 
        "Schezwan Chicken Fried Rice", "Schezwan Egg Fried Rice", "Veg Noodles", "Chicken Noodles", 
        "Egg Noodles", "Veg Hakka Noodles",  "Chicken Hakka Noodles", "Egg Hakka Noodles"
    ],
    "Chinese Appetizers": [
        "Veg Spring Rolls", "Chicken Spring Rolls", "Veg Dim Sum", "Chicken Dim Sum", "Veg Manchurian Dry", "Chicken Manchurian Dry", 
        "Chilli Chicken Dry", "Chilli Paneer Dry", "Egg Manchurian Dry", "Egg Chilli Dry", "Chicken Lollipop"
    ],
    "Chinese Complements": [
        "Chilli Chicken Gravy", "Chilli Paneer Gravy", "Egg Manchurian Gravy", "Egg Chilli Gravy", "Chicken Manchurian Gravy",
        "Veg Manchurian Gravy", "Schezwan Chicken Gravy", "Schezwan Paneer Gravy", "Schezwan Egg Gravy"
    ], 
    "Chinese Extras": [
        "Extra Schezwan Sauce", "Extra Soy Sauce", "Extra Chilli Vinegar", "Extra Chilli Oil", "Extra Manchurian Gravy"
    ],
    "Chinese Desserts & beverages": [
        "Green Tea", "Black Tea", "Lemon Tea", "Egg Custard Buns", "Vanilla Ice Cream", "Chocolate Ice Cream", 
        "Vanilla Milkshake", "Chocolate Milkshake"
    ],


    "Fast Food Mains": [
        "Veg Burger", "Chicken Burger", "Aloo Burger", "Veg Wrap", "Chicken Wrap", "Egg Wrap", "Paneer Wrap", 
        "Veg Sandwich", "Chicken Sandwich", "Egg Sandwich"
    ],
    "Fast Food Appetizers": [
        "Chicken Nuggets", "Veg Nuggets", "Potato Wedges", "Chicken Popcorn", "Veg Popcorn",
        "Chicken Wings", "Chicken Momos", "Veg Momos"
    ],
    "Fast Food Complements": [
        "French Fries", "Loaded Fries", "Cheese Fries", "Onion Rings", "Baked Beans"
    ],
    "Fast Food Extras": [
        "Extra Cheese", "Ketchup", "Mayonnaise", "Mustard", "Peri Peri Sauce", "BBQ Sauce", 
        "Cheese Dip", "Garlic Dip", "Sour Cream Dip"
    ],
    "Fast Food Desserts & beverages": [
        "Chocolate Milkshake", "Vanilla Milkshake", "Strawberry Milkshake", "Coke", "7UP",
        "Vanilla Ice Cream", "Chocolate Ice Cream", "Brownie Sundae", "Mojito", "Choco Lava Cake"
    ],


    "Healthy Mains": [
        "Veg Salad", "Chicken Salad", "Paneer Salad", "Egg Salad", "Greek Salad", "Chicken Caesar Salad", "Quinoa Salad", 
        "Protein Bowl Veg", "Protein Bowl Chicken", "Brown Rice Veg Bowl", "Grilled Chicken Bowl", "Egg Rice Bowl"
    ],
    "Healthy Appetizers": [
        "Fruit Salad", "Mixed Nuts", "Roasted Chickpeas", "Edamame Beans", "Egg White Omelette", "Grilled Chicken Strips", 
        "Egg Sandwich"
    ],
    "Healthy Complements": [
        "Lemon Wedges", "Chia Seeds", "Flax Seeds", "Peanut Butter", "Boiled Egg", "Avocado Slices", "Tofu Cubes"
    ],
    "Healthy Extras": [
        "Extra Avocado", "Extra Chicken", "Extra Paneer", "Extra Egg"
    ],
    "Healthy Desserts & beverages": [
        "Chia Pudding", "Protein Bar", "Almond Milk Smoothie", "Green Tea", "Black Coffee",
        "Mango Smoothie", "Strawberry Smoothie", "Protein Shake Chocolate", "Protein Shake Vanilla",
    ] 
}

## Build the menu dataframe

### Building scripts for labelling the items in the menu

In [757]:
def classify_veg_type(item):
    item = item.lower()
    
    if any(x in item for x in ["chicken", "mutton", "fish", "prawn"]):
        return "nonveg"

    elif "egg" in item:
        return "egg"

    else:
        return "veg"

In [758]:
def extract_cuisine_and_course(category, cuisines_list):
    category_lower = category.lower()
    cuisine_match = None
    
    for cuisine in cuisines_list:
        if category_lower.startswith(cuisine.lower()):
            cuisine_match = cuisine
            break
    
    if cuisine_match is None:
        raise ValueError(f"Unknown cuisine in category: {category}")
    
    course = category_lower.replace(cuisine_match.lower(), "").strip()
    
    return cuisine_match, course

### Building the menu (without prices)

In [759]:
menu_rows = []
item_id = 0

for category, items in cuisine_items.items():

    cuisine, course = extract_cuisine_and_course(category, cuisines)

    for item in items:

        veg_type = classify_veg_type(item)

        menu_rows.append({
            "Item ID": item_id,
            "Item Name": item,
            "Cuisine": cuisine,
            "Course": course,
            "Veg Type": veg_type
        })

        item_id += 1

menu_df = pd.DataFrame(menu_rows)

In [760]:
print(menu_df.head())

   Item ID         Item Name       Cuisine Course Veg Type
0        0  Amritsari Kulcha  North Indian  mains      veg
1        1        Jeera Rice  North Indian  mains      veg
2        2         Veg Pulao  North Indian  mains      veg
3        3    Lachha Paratha  North Indian  mains      veg
4        4       Garlic Naan  North Indian  mains      veg

In [761]:
print("\nTotal items:", len(menu_df))

print("\nVeg distribution:")
print(menu_df["Veg Type"].value_counts())

print("\nCourse distribution:")
print(menu_df["Course"].value_counts())

print("\nCuisine distribution:")
print(menu_df["Cuisine"].value_counts())

Total items: 351

Veg distribution:
Veg Type
veg       232
nonveg     75
egg        44
Name: count, dtype: int64

Course distribution:
Course
mains                   101
appetizers               71
complements              66
desserts & beverages     58
extras                   55
Name: count, dtype: int64

Cuisine distribution:
Cuisine
Biryani         64
South Indian    57
North Indian    56
Italian         48
Chinese         45
Fast Food       42
Healthy         39
Name: count, dtype: int64

In [762]:
# Building a dictionary for easy look up
item_veg_type_map = dict(zip(menu_df["Item ID"], menu_df["Veg Type"]))

### Generating prices for the items in the menu

In [763]:
course_base_price = {
    "mains": 150,
    "appetizers": 250,
    "complements": 100,
    "extras": 50,
    "desserts & beverages": 110
}

cuisine_multiplier = {
    "North Indian": 1.0,
    "South Indian": 0.85,
    "Biryani": 1.2,
    "Chinese": 1.1,
    "Italian": 1.4,
    "Fast Food": 0.9,
    "Healthy": 1.2
}

cuisine_course_override = {
    ("Italian", "mains"): 250,
    ("Biryani", "mains"): 200,
    ("North Indian", "complements"): 200,
    ("Chinese", "complements"): 200,
    ("Italian", "complements"): 80,
    ("South Indian", "complements"): 80,
    ("Italian", "appetizers"): 150,
    ("South Indian", "appetizers"): 150,
}

tier_multiplier = {
    "Budget": 0.85,
    "Premium": 1.25
}

In [764]:
def item_multiplier(item_name):
    name = item_name.lower()
    modifier = 1.0

    if "plain" in name:
        modifier *= 0.90

    if "butter" in name:
        modifier *= 1.15

    if "cheese" in name:
        modifier *= 1.20

    if "paneer" in name:
        modifier *= 1.18

    if "chicken" in name:
        modifier *= 1.25

    if "mutton" in name:
        modifier *= 1.45

    if "fish" in name:
        modifier *= 1.60

    if "egg" in name:
        modifier *= 1.05

    return modifier

In [765]:
def get_base_price(cuisine, course):
    # Check override first
    if (cuisine, course) in cuisine_course_override:
        return cuisine_course_override[(cuisine, course)]

    base = course_base_price[course]
    mult = cuisine_multiplier.get(cuisine, 1.0)

    return base * mult


def get_multiplier(item_name):
    item_modifier = item_multiplier(item_name)

    return item_modifier

### Adding prices column to the menu

In [766]:
menu_df["Base Price"] = menu_df.apply(lambda row: get_base_price(row["Cuisine"], row["Course"]), axis = 1)
menu_df["Base Multiplier"] = menu_df.apply(lambda row: get_multiplier(row["Item Name"]), axis = 1)

menu_df['Budget Price'] = (menu_df["Base Price"] * menu_df["Base Multiplier"] * tier_multiplier["Budget"]).astype(int)
menu_df['Premium Price'] = (menu_df["Base Price"] * menu_df["Base Multiplier"] * tier_multiplier["Premium"]).astype(int)

In [767]:
menu_df.head()

,Item ID,Item Name,Cuisine,Course,Veg Type,Base Price,Base Multiplier,Budget Price,Premium Price
0,0,Amritsari Kulcha,North Indian,mains,veg,150.0,1.0,127,187
1,1,Jeera Rice,North Indian,mains,veg,150.0,1.0,127,187
2,2,Veg Pulao,North Indian,mains,veg,150.0,1.0,127,187
3,3,Lachha Paratha,North Indian,mains,veg,150.0,1.0,127,187
4,4,Garlic Naan,North Indian,mains,veg,150.0,1.0,127,187

### Adding a $\text{Popularity Score}$ for cold starting

In [768]:
def generate_popularity(menu, seed = 42):
    np.random.seed(seed)
    menu["Popularity Score"] = np.random.lognormal(mean = 0.0, sigma = 1.0, size = len(menu))
    
    # Normalize to 0–1
    menu["Popularity Score"] = (menu["Popularity Score"] - 
                                menu["Popularity Score"].min()) / (menu["Popularity Score"].max() - 
                                                                   menu["Popularity Score"].min())
    
    return menu

In [769]:
menu_df = generate_popularity(menu_df)
menu_df.head()

,Item ID,Item Name,Cuisine,Course,Veg Type,Base Price,Base Multiplier,Budget Price,Premium Price,Popularity Score
0,0,Amritsari Kulcha,North Indian,mains,veg,150.0,1.0,127,187,0.034072
1,1,Jeera Rice,North Indian,mains,veg,150.0,1.0,127,187,0.017666
2,2,Veg Pulao,North Indian,mains,veg,150.0,1.0,127,187,0.039760
3,3,Lachha Paratha,North Indian,mains,veg,150.0,1.0,127,187,0.096575
4,4,Garlic Naan,North Indian,mains,veg,150.0,1.0,127,187,0.015975

In [770]:
menu_df.to_csv(BASE_DIR + "/Data Generation/Data/zomato_menu.csv", index = False)

## Generate Customers Table

##### While features like $\text{Cuisine Preference}$, $\text{Veg Nonveg Egg Preference}$, $\text{App Usage Frequency}$, $\text{Course Preference}$ and $\text{Item Preference}$ should ideally be derived variables from the $\text{Orders Table}$, it is much easier to generate the $\text{Orders Table}$ if these features are already available. $\\[0.1in]$ Therefore, we have assumed that these feature already exist in the $\text{Customers Table}$. We can always generate these features if we have the original orders dataset.

### Generating customer's preferences to help build the $\text{Orders Table}$

In [771]:
def generate_veg_pref():
    r = np.random.rand()
    
    # 20% pure veg
    if r < 0.20:
        return [1.0, 0.0, 0.0]

    # 15% veg + egg only
    elif r < 0.35:
        veg_egg = np.random.dirichlet([3, 1])  # bias toward veg
        return [veg_egg[0], 0.0, veg_egg[1]]

    # remaining 65% mixed
    else:
        mixed = np.random.dirichlet([2, 3, 1])  # slight nonveg bias
        return mixed.tolist()

In [772]:
print(time_categories)

['late night', 'breakfast', 'lunch', 'snack', 'dinner']

In [773]:
def generate_time_pref():
    r = np.random.rand()

    # 12% Late-night users
    if r < 0.12:
        probs = np.random.dirichlet([4, 2, 1, 3, 1])  # late night dominant

    # 88% Non-late-night users
    else:
        probs = np.random.dirichlet([0.2, 3, 2, 4, 2])
        probs[0] = 0
        probs = probs / probs.sum()  # re-normalize to sum to 1

    return probs.tolist()

In [774]:
city_cuisine_alpha = {
    "Delhi": [4, 1, 2, 1, 1, 1, 1],
    "Mumbai": [3, 3, 2, 4, 1, 1, 4],
    "Bangalore": [2, 4, 2, 2, 1, 2, 4],
    "Chennai": [1, 4, 2, 1, 2, 1, 2],
}


def generate_cuisine_pref(city, age):
    # Base city alpha
    base_alpha = np.array(city_cuisine_alpha.get(city, np.ones(len(cuisines))), dtype = float)

    alpha = base_alpha.copy()

    # AGE EFFECTS

    if age < 25:    # boost fast food, biryani, italian
        alpha[cuisines.index("Fast Food")] += 2
        alpha[cuisines.index("Biryani")] += 2
        alpha[cuisines.index("Italian")] += 1

    elif 25 <= age < 40:    # mild boost to fast food, chinese, biryani and italian
        alpha[cuisines.index("Fast Food")] += 1.25
        alpha[cuisines.index("Chinese")] += 1
        alpha[cuisines.index("Biryani")] += 1.25
        alpha[cuisines.index("Italian")] += 1

    elif 40 <= age < 55:    # mild reduction in fast food
        alpha[cuisines.index("North Indian")] += 2
        alpha[cuisines.index("South Indian")] += 2
        alpha[cuisines.index("Fast Food")] *= 0.75

    else:   # significant reduction fast food
        alpha[cuisines.index("South Indian")] += 2
        alpha[cuisines.index("Fast Food")] *= 0.15

    # Ensure no zeros
    alpha = np.maximum(alpha, 0.1)

    probs = np.random.dirichlet(alpha)

    return probs.tolist()

In [775]:
print(cuisines)

['North Indian', 'South Indian', 'Biryani', 'Italian', 'Chinese', 'Fast Food', 'Healthy']

In [776]:
base_course_alpha = {
    "mains": 3,
    "appetizers": 2,
    "complements": 2,
    "extras": 1,
    "desserts & beverages": 2
}


def generate_course_pref(customer):
    alpha = base_course_alpha.copy()
    age = customer["Age"]
    city = customer["City"]
    avg_value = customer["Avg Value per Item"]
    time_probs = np.array(json.loads(customer["Time Preference"]))
    dominant_time = time_categories[np.argmax(time_probs)]

    # Time effect
    if dominant_time == "dinner":
        alpha["mains"] += 2
        alpha["complements"] += 1
    if dominant_time == "snack":
        alpha["desserts & beverages"] += 2
        alpha["appetizers"] += 1
    if dominant_time == "late night":
        alpha["desserts & beverages"] += 2

    # Age effect
    if age < 25:
        alpha["extras"] += 1
        alpha["desserts & beverages"] += 1
    if age > 40:
        alpha["mains"] += 1

    # High spending effect
    if avg_value > 400:
        alpha["appetizers"] += 1
        alpha["desserts & beverages"] += 1

    # City effect
    if city == "Mumbai":
        alpha["appetizers"] += 1
    if city == "Chennai":
        alpha["mains"] += 1

    alpha_vector = [alpha[c] for c in courses]

    return np.random.dirichlet(alpha_vector).tolist()

In [777]:
def item_score(row, cust, order_time_category):
    score = 1.0

    # Veg Compatibility
    veg_probs = np.array(json.loads(cust["Veg Nonveg Egg Preference"]))
    veg_type = row["Veg Type"]

    if veg_type == "veg":
        score *= (0.1 + veg_probs[0])
    elif veg_type == "nonveg":
        score *= (0.1 + veg_probs[1])
    else:
        score *= (0.1 + veg_probs[2])

    # Prevent zero collapse
    score = max(score, 1e-6)


    # Price Compatibility (smooth Gaussian)
    avg_value = cust["Avg Value per Item"]
    price = row["Base Price"]

    sigma = avg_value * 0.4  # adaptive spread
    price_weight = np.exp(-((price - avg_value) ** 2) / (2 * sigma ** 2))
    score *= price_weight


    # Age Effects
    age = cust["Age"]

    if age < 25:
        if row["Course"] in ["desserts & beverages", "appetizers"]:
            score *= 1.5
        if row["Cuisine"] == "Fast Food":
            score *= 1.3
        if row["Cuisine"] == "Biryani":
            score *= 1.5
        if row["Cuisine"] == "Healthy Food":
            score *= 1.2


    elif age > 45:
        if row["Cuisine"] == "South Indian":
            score *= 1.3
        if row["Cuisine"] == "North Indian":
            score *= 1.3
        if row["Course"] == "desserts & beverages":
            score *= 0.45
        if row["Course"] == "appetizers":
            score *= 0.65

    
    # Time-of-Day Effects
    if order_time_category == "breakfast":
        if row["Course"] == "mains":
            score *= 1.3

    if order_time_category == "snack":
        if row["Course"] in ["desserts & beverages", "appetizers"]:
            score *= 1.4
    
    if order_time_category == "lunch":
        if row["Course"] == "mains":
            score *= 1.5
        if row["Course"] == "complements":
            score *= 1.2

    if order_time_category == "dinner":
        if row["Course"] == "mains":
            score *= 1.5
        if row["Course"] == "complements":
            score *= 1.2

    if order_time_category == "late night":
        if row["Course"] == "desserts & beverages":
            score *= 1.6


    # City Preference
    cuisine_probs = np.array(json.loads(cust["Cuisine Preference"]))
    cuisine_index = cuisines.index(row["Cuisine"])
    score *= (0.5 + cuisine_probs[cuisine_index])

    
    # Course Preference Reinforcement
    course_probs = np.array(json.loads(cust["Course Preference"]))
    course_index = courses.index(row["Course"])
    score *= (0.5 + course_probs[course_index])

    
    # Small Random Noise (heterogeneity)
    score *= np.random.normal(1.0, 0.05)

    return max(score, 1e-8)

### Generating the $\text{Customers Table}$

In [778]:
customers = []

for i in range(N_CUSTOMERS):

    city = np.random.choice(cities)
    age = int(max(18, np.random.normal(30, 15)))
    cuisine_probs = generate_cuisine_pref(city, age)

    customers.append({
        "Customer ID": 100001 + i,
        "City": city,
        "Age": int(max(18, np.random.normal(30, 15))),
        "Cuisine Preference": json.dumps(cuisine_probs),
        "Veg Nonveg Egg Preference": json.dumps(generate_veg_pref()),
        "App Usage Frequency": np.random.choice(["low", "medium", "high"], p = [0.4, 0.5, 0.1]),
        "Avg Value per Item": int(min(max(250, np.random.normal(250, 100)), 800)),
        "Avg Items": int(min(max(1, np.random.normal(6, 2)), 12)),
        "Time Preference": json.dumps(generate_time_pref()),
    })

customers_df = pd.DataFrame(customers)

In [779]:
customers_df.columns

Index(['Customer ID', 'City', 'Age', 'Cuisine Preference',
       'Veg Nonveg Egg Preference', 'App Usage Frequency',
       'Avg Value per Item', 'Avg Items', 'Time Preference'],
      dtype='object')

In [780]:
customers_df['Avg Order Value'] = customers_df['Avg Items'] * customers_df['Avg Value per Item']
customers_df["Course Preference"] = customers_df.apply(lambda row: json.dumps(generate_course_pref(row)), axis = 1)

### Rounding to 2 decimal places

In [781]:
def round_and_fix_probs(prob_list, decimals=2):

    probs = np.array(prob_list)
    rounded = np.round(probs, decimals)

    diff = 1.0 - rounded.sum()

    idx = np.argmax(rounded)
    rounded[idx] += diff

    rounded = np.round(rounded, decimals)

    return [float(f"{x:.2f}") for x in rounded]

In [782]:
customers_df["Veg Nonveg Egg Preference"] = customers_df["Veg Nonveg Egg Preference"].apply(lambda x: json.dumps(round_and_fix_probs(json.loads(x), 2)))
customers_df["Cuisine Preference"] = customers_df["Cuisine Preference"].apply(lambda x: json.dumps(round_and_fix_probs(json.loads(x), 2)))
customers_df["Time Preference"] = customers_df["Time Preference"].apply(lambda x: json.dumps(round_and_fix_probs(json.loads(x), 2)))
customers_df['Course Preference'] = customers_df["Course Preference"].apply(lambda x: json.dumps(round_and_fix_probs(json.loads(x), 2)))

In [783]:
print(customers_df.shape)
customers_df.head()

(2000, 11)

,Customer ID,City,Age,Cuisine Preference,Veg Nonveg Egg Preference,App Usage Frequency,Avg Value per Item,Avg Items,Time Preference,Avg Order Value,Course Preference
0,100001,Delhi,18,"[0.28, 0.08, 0.32, 0.1, 0.12, 0.08, 0.02]","[0.16, 0.52, 0.32]",high,250,7,"[0.54, 0.06, 0.02, 0.14, 0.24]",1750,"[0.12, 0.28, 0.13, 0.01, 0.46]"
1,100002,Mumbai,35,"[0.41, 0.12, 0.01, 0.1, 0.14, 0.18, 0.04]","[0.26, 0.55, 0.19]",low,250,5,"[0.0, 0.21, 0.33, 0.31, 0.15]",1250,"[0.53, 0.18, 0.05, 0.16, 0.08]"
2,100003,Mumbai,38,"[0.08, 0.07, 0.1, 0.19, 0.08, 0.16, 0.32]","[0.48, 0.39, 0.13]",medium,254,6,"[0.0, 0.14, 0.4, 0.29, 0.17]",1524,"[0.3, 0.2, 0.08, 0.15, 0.27]"
3,100004,Bangalore,25,"[0.07, 0.18, 0.11, 0.1, 0.02, 0.15, 0.37]","[1.0, 0.0, 0.0]",low,250,4,"[0.0, 0.12, 0.19, 0.46, 0.23]",1000,"[0.36, 0.1, 0.13, 0.04, 0.37]"
4,100005,Delhi,53,"[0.29, 0.0, 0.32, 0.13, 0.02, 0.23, 0.01]","[1.0, 0.0, 0.0]",low,336,6,"[0.0, 0.19, 0.05, 0.68, 0.08]",2016,"[0.21, 0.18, 0.09, 0.27, 0.25]"

In [784]:
customers_df.to_csv(BASE_DIR + "/Data Generation/Data/zomato_customers.csv", index = False)

## Generate Orders Table

### Initialzing the Parameters

In [785]:
P_MAIN = 0.85

P_APPETIZER_IF_MAIN = 0.40
P_COMPLEMENT_IF_MAIN = 0.80
P_EXTRA_IF_MAIN = 0.60
P_DESSERT_IF_MAIN = 0.20

P_APPETIZER_IF_NO_MAIN = 0.75
P_COMPLEMENT_IF_NO_MAIN = 0.10
P_EXTRA_IF_NO_MAIN = 0.00
P_DESSERT_IF_NO_MAIN = 0.20

In [786]:
# Item selection Logic

prob_table_if_main = {
    "mains": 0.05,  # allow for multiple mains in some cases
    "appetizers": P_APPETIZER_IF_MAIN,
    "complements": P_COMPLEMENT_IF_MAIN,
    "extras": P_EXTRA_IF_MAIN,
    "desserts & beverages": P_DESSERT_IF_MAIN
}

prob_table_if_no_main = {
    "mains": P_MAIN,
    "appetizers": P_APPETIZER_IF_NO_MAIN,
    "complements": P_COMPLEMENT_IF_NO_MAIN,
    "extras": P_EXTRA_IF_NO_MAIN,
    "desserts & beverages": P_DESSERT_IF_NO_MAIN
}

In [787]:
usage_weights = {"high": 0.6,
                 "medium": 0.3,
                 "low": 0.2}

### Defining the necessary functions for orders generation

In [788]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

In [789]:
def generate_time_from_pref(cust):
    time_probs = np.array(json.loads(cust["Time Preference"]))
    category = np.random.choice(time_categories, p = time_probs)

    start_hour, end_hour = time_ranges[category]

    # handle midnight wrap
    if start_hour > end_hour:
        if random.random() < 0.5:
            hour = random.randint(start_hour, 23)
        else:
            hour = random.randint(0, end_hour)
    else:
        # normal peak-based generation
        peak = (start_hour + end_hour) // 2
        hour = int(np.clip(np.random.normal(peak, 1), start_hour, end_hour))

    minute = random.randint(0, 59)
    second = random.randint(0, 59)

    return hour, minute, second

In [790]:
def ordered_items(cuisine, items_number, customer):
    selected_items = []
    selected_item_ids = set()

    veg_probs = np.array(json.loads(customer["Veg Nonveg Egg Preference"]))
    course_probs = np.array(json.loads(customer["Course Preference"]))

    for _ in range(items_number):

        # Sample course using customer preference
        course = np.random.choice(courses, p = course_probs)

        # Filter menu by cuisine + course
        subset = menu_df[
            (menu_df["Cuisine"] == cuisine) &
            (menu_df["Course"] == course) &
            (~menu_df["Item ID"].isin(selected_item_ids))
        ]

        if subset.empty:
            continue

        # Score items
        scores = subset.apply(lambda row: item_score(row, customer, time_categories), axis = 1).values

        if scores.sum() <= 1e-12:
            probs = np.ones(len(subset)) / len(subset)
        
        else:
            probs = scores / scores.sum()

        chosen_item = np.random.choice(subset["Item ID"], p = probs)

        selected_items.append(chosen_item)
        selected_item_ids.add(chosen_item)

    return selected_items

In [791]:
def recommended_items(cuisine, items_ordered, n_recommend = 3):
    cuisine_menu = menu_df[menu_df["Cuisine"] == cuisine]

    # Removing already ordered items
    candidate_menu = cuisine_menu[~cuisine_menu["Item ID"].isin(items_ordered)]

    # Identify what courses are already ordered
    ordered_courses = cuisine_menu[cuisine_menu["Item ID"].isin(items_ordered)]["Course"].unique().tolist()
    has_main = "mains" in ordered_courses

    if has_main:
        rec_probs = prob_table_if_main
    else:
        rec_probs = prob_table_if_no_main

    recommended_ids = []
    recommended_names = []


    while len(recommended_ids) < n_recommend:
        categories = list(rec_probs.keys())
        probs = np.array(list(rec_probs.values()))
        probs = probs / probs.sum()

        chosen_category = np.random.choice(categories, p = probs)

        subset = candidate_menu[
            (candidate_menu["Course"] == chosen_category) &
            (~candidate_menu["Item ID"].isin(recommended_ids))
        ]

        if len(subset) == 0:
            continue

        item_id = subset.sample(1)["Item ID"].iloc[0]
        item_name = subset[subset["Item ID"] == item_id]["Item Name"].iloc[0]

        recommended_ids.append(item_id)
        recommended_names.append(item_name)

    return recommended_ids, recommended_names

In [792]:
item_course_map = dict(zip(menu_df["Item ID"], menu_df["Course"]))
item_cuisine_map = dict(zip(menu_df["Item ID"], menu_df["Cuisine"]))

item_popularity = {item: np.random.uniform(0.2, 1.0) for item in menu_df["Item ID"]}

In [793]:
complement_rules = {
    "mains": ["appetizers", "complements", "extras", "desserts & beverages"],
    "appetizers": ["mains", "desserts & beverages"],
    "complements": ["mains"],
    "extras": ["mains", "appetizers"],
    "desserts & beverages": ["mains", "appetizers"]
}

In [794]:
def recommendation_click_probability(cust, ordered_ids, rec_id, position):
    ordered_courses = {item_course_map[i] for i in ordered_ids}

    rec_course = item_course_map[rec_id]
    rec_cuisine = item_cuisine_map[rec_id]

    # Complement score
    complement_score = max(
        [rec_course in complement_rules.get(course, [])
        for course in ordered_courses],
        default = False
    )

    complement_score = 0.6 if complement_score else 0.15

    # Cuisine match score
    cuisine_match = 0.6 if rec_cuisine in cuisines else 0.3

    # User engagement
    usage_score = {
        "low": 0.2,
        "medium": 0.4,
        "high": 0.7
    }[cust["App Usage Frequency"]]

    # Position bias
    position_score = 1/ (position + 1)

    # Popularity
    popularity_score = item_popularity.get(rec_id, 0.5) * 0.6

    # Basket size influence
    basket_score = min(len(ordered_ids)/ 8, 0.6)

    intercept = -2.2

    # Final score
    score = (
        intercept +
        1.0 * complement_score +
        0.7 * cuisine_match +
        0.9 * usage_score +
        0.8 * position_score +
        0.6 * popularity_score +
        0.5 * basket_score +
        np.random.normal(0, 0.4)
    )

    return sigmoid(score)

In [795]:
def recommendation_click_probability(cust, ordered_ids, rec_id, position, menu, complement_rules):
    ordered_df = menu[menu["Item ID"].isin(ordered_ids)]
    rec_row = menu[menu["Item ID"] == rec_id].iloc[0]

    ordered_courses = set(ordered_df["Course"])
    ordered_cuisines = set(ordered_df["Cuisine"])

    rec_course = rec_row["Course"]
    rec_cuisine = rec_row["Cuisine"]

    popularity_score = rec_row["Popularity Score"]

    basket_size = len(ordered_ids)

    # Complement score
    num_complements = sum(
        rec_course in complement_rules.get(course, [])
        for course in ordered_courses
    )

    complement_score = num_complements / max(len(ordered_courses), 1)

    # Cuisine score
    cuisine_score = 1.0 if rec_cuisine in ordered_cuisines else 0.0

    # Usage score
    usage_score_map = {
        "low": 0.3,
        "medium": 0.6,
        "high": 1.0
    }
    usage_score = usage_score_map.get(
        cust.get("App Usage Frequency", "medium"),
        0.6
    )

    # Position bias
    position_score = 1 / np.log2(position + 2)

    # Basket stage
    basket_score = min(basket_size / 8.0, 1.0)

    # Logistic model
    intercept = -2.5

    score = (
        intercept
        + 1.2 * complement_score
        + 0.9 * cuisine_score
        + 0.8 * usage_score
        + 1.0 * position_score
        + 0.7 * popularity_score
        + 0.6 * basket_score
    )

    return 1 / (1 + np.exp(-score))

In [796]:
def simulate_recommendation_click(cust, ordered_ids, recommendation_ids):
    clicked = []

    # Check if order is strictly veg
    ordered_veg_types = [item_veg_type_map[i] for i in ordered_ids]

    all_veg_order = all(v == "veg" for v in ordered_veg_types)

    for pos, rec_id in enumerate(recommendation_ids, start = 1):

        rec_veg_type = item_veg_type_map[rec_id]

        # On veg days, customer won't click on non veg recommendation
        if all_veg_order and (rec_veg_type == "nonveg" or rec_veg_type == "egg"):
            clicked.append(0)
            continue

        prob = recommendation_click_probability(cust, ordered_ids, rec_id, pos, menu_df, complement_rules)

        if np.random.rand() < prob:
            if np.random.rand() < 0.55:
                clicked.append(1)
            else:
                clicked.append(0)
        else:
            clicked.append(0)

    return clicked

### Simulating the $\text{Orders Table}$

In [797]:
orders = []

for i in range(N_ORDERS):

    # A random customer is chosen to place an order, with higher probability for more frequent app users
    customer = customers_df.sample(1,
                               weights = customers_df["App Usage Frequency"].map(usage_weights)
                               ).iloc[0]
    
    date_part = fake.date_time_between(start_date = "-1y", end_date = "now")
    hour, minute, second = generate_time_from_pref(customer)

    order_datetime = date_part.replace(hour = hour, minute = minute, second = second)
    order_time = order_datetime


    # Extract cuisine probability vector
    cat_probs = np.array(json.loads(customer["Cuisine Preference"]))

    # Choose cuisine using those probabilities
    cuisine = np.random.choice(cuisines, p = cat_probs)
    course_probs = np.array(json.loads(customer["Course Preference"]))
    

    # Choose veg type using veg/nonveg/egg probabilities
    veg_probs = np.array(json.loads(customer["Veg Nonveg Egg Preference"]))
    veg_type = np.random.choice(veg_types, p = veg_probs)

    items_number = int(min(max(2, np.random.normal(customer["Avg Items"], 3)), 8))
    items_ordered_ids = ordered_items(cuisine, items_number, customer)

    recommendation_ids, recommended_names = recommended_items(cuisine, items_ordered_ids, n_recommend = 3)

    recommendation_added = False

    if recommendation_ids:
        top_cuisine = cuisines[np.argmax(cat_probs)]
        match = int(cuisine == top_cuisine)
        score = (
            1.5 * match +
            0.5 * (customer["App Usage Frequency"] == "high") +
            np.random.normal(0,1)
        )


    recommendation_added = simulate_recommendation_click(customer, items_ordered_ids, recommendation_ids)
    
    orders.append({
        "Order ID": 8000000 + i,
        "Customer ID": customer["Customer ID"],
        "Order Time": order_time,
        "Cuisine": cuisine,
        "Items Ordered ID": items_ordered_ids,
        "Items Ordered Name": menu_df[menu_df["Item ID"].isin(items_ordered_ids)]["Item Name"].tolist(),
        "Recommendation Shown ID": recommendation_ids,
        "Recommendation Shown Name": recommended_names,
        "Recommendation Added 1": recommendation_added[0],
        "Recommendation Added 2": recommendation_added[1],
        "Recommendation Added 3": recommendation_added[2],
    })

orders_df = pd.DataFrame(orders)

In [798]:
print(orders_df.shape)
orders_df.head()

(100000, 11)

,Order ID,Customer ID,Order Time,Cuisine,Items Ordered ID,Items Ordered Name,Recommendation Shown ID,Recommendation Shown Name,Recommendation Added 1,Recommendation Added 2,Recommendation Added 3
0,8000000,100682,2025-08-19 13:17:17.719899,Fast Food,"[290, 297, 275]","[Egg Wrap, Cheese Fries, Peri Peri Sauce]","[303, 285, 289]","[Vanilla Milkshake, Chicken Wings, Loaded Fries]",0,0,0
1,8000001,100788,2025-07-06 07:46:39.936323,Healthy,"[313, 325, 340, 334, 341, 338, 339]","[Chicken Salad, Mixed Nuts, Peanut Butter, Ext...","[336, 335, 331]","[Avocado Slices, Boiled Egg, Lemon Wedges]",1,1,1
2,8000002,101649,2025-06-28 18:55:40.807849,Chinese,"[248, 262, 264, 267, 240, 260]","[Chicken Dim Sum, Chilli Chicken Gravy, Extra ...","[241, 268, 238]","[Veg Manchurian Dry, Vanilla Milkshake, Chicke...",0,1,0
3,8000003,100351,2025-03-15 19:09:54.842288,Healthy,"[343, 332, 313, 331, 333, 314, 340, 345]","[Chicken Salad, Paneer Salad, Lemon Wedges, Ch...","[334, 339, 336]","[Peanut Butter, Extra Chicken, Avocado Slices]",1,1,0
4,8000004,101636,2025-09-06 13:35:45.712040,Italian,"[219, 189, 185, 218, 224, 217]","[Red Sauce Pasta (Veg), Garlic Bread, Tiramisu...","[216, 203, 209]","[Coleslaw, Marinara Sauce, Oregano]",1,0,1

In [799]:
orders_df.to_csv(BASE_DIR + "/Data Generation/Data/zomato_orders.csv", index = False)

## Sanity Checking the Click Through Rate

In [800]:
print('CTR of recommendation 1:', round(orders_df['Recommendation Added 1'].sum()/len(orders_df) * 100, 2),'%')
print('CTR of recommendation 2:', round(orders_df['Recommendation Added 2'].sum()/len(orders_df) * 100, 2),'%')
print('CTR of recommendation 3:', round(orders_df['Recommendation Added 3'].sum()/len(orders_df) * 100, 2),'%')

CTR of recommendation 1: 29.61 %
CTR of recommendation 2: 27.9 %
CTR of recommendation 3: 27.42 %

## Recalculating key features based on observed data

### Train-test split based on chronology

In [801]:
def chronological_split(df, time_col = "Order Time", test_ratio = 0.2):
    df = df.sort_values(time_col)

    cutoff_index = int(len(df) * (1 - test_ratio))
    cutoff_time = df.iloc[cutoff_index][time_col]

    train = df[df[time_col] <= cutoff_time].copy()
    test  = df[df[time_col] > cutoff_time].copy()

    return train, test

In [802]:
train_df, test_df = chronological_split(orders_df)

### Reloading the data files and replacing columns with observed data

In [803]:
customers_df = pd.read_csv(BASE_DIR + "/Data Generation/Data/zomato_customers.csv")
orders_df = pd.read_csv(BASE_DIR + "/Data Generation/Data/zomato_orders.csv")
menu_df = pd.read_csv(BASE_DIR + "/Data Generation/Data/zomato_menu.csv")

In [804]:
customers_df.drop(columns = ['Avg Value per Item', 'Avg Items', 'Avg Order Value'], inplace = True)
menu_df.drop(columns = ['Popularity Score'], inplace = True)

menu_df.head()

,Item ID,Item Name,Cuisine,Course,Veg Type,Base Price,Base Multiplier,Budget Price,Premium Price
0,0,Amritsari Kulcha,North Indian,mains,veg,150.0,1.0,127,187
1,1,Jeera Rice,North Indian,mains,veg,150.0,1.0,127,187
2,2,Veg Pulao,North Indian,mains,veg,150.0,1.0,127,187
3,3,Lachha Paratha,North Indian,mains,veg,150.0,1.0,127,187
4,4,Garlic Naan,North Indian,mains,veg,150.0,1.0,127,187

### Calculating order metrics

In [805]:
def add_order_metrics(orders_df, menu_df):
    df = orders_df.copy()

    # Ensure items_ordered is a list
    def ensure_list(x):
        if isinstance(x, list):
            return x
        return ast.literal_eval(x)

    df["Items Ordered ID"] = df["Items Ordered ID"].apply(ensure_list)

    # Explode
    exploded = df.explode("Items Ordered ID")

    # Merge prices
    exploded = exploded.merge(
        menu_df[["Item ID", "Budget Price"]],
        left_on = "Items Ordered ID",
        right_on = "Item ID",
        how = "left"
    )

    exploded["price"] = exploded["Budget Price"].fillna(0)

    # Aggregate
    summary = (
        exploded.groupby("Order ID")
        .agg(
            order_value = ("Budget Price", "sum"),
            num_items = ("Items Ordered ID", "count")
        )
        .reset_index()
    )

    # Merge back
    df = df.merge(summary, on = "Order ID", how = "left")

    # Rename the columns
    df = df.rename(columns = {
        "order_value": "Order Value",
        "num_items": "Number of Items"
    })
    
    return df

In [806]:
train_df = add_order_metrics(train_df, menu_df)

### Calculating popularity score for items in menu

In [807]:
def compute_item_popularity(train_df):
    df = train_df.copy()

    # Ensure list format
    def ensure_list(x):
        if isinstance(x, list):
            return x
        return ast.literal_eval(x)

    df["Items Ordered ID"] = df["Items Ordered ID"].apply(ensure_list)

    # Explode items
    exploded = df.explode("Items Ordered ID")

    # Count frequency
    item_counts = (
        exploded
        .groupby("Items Ordered ID")
        .size()
        .reset_index(name = "Order Count")
    )

    return item_counts

In [808]:
def normalize_popularity(item_counts):
    item_counts["Popularity Score"] = (
        item_counts["Order Count"] - 
        item_counts["Order Count"].min()) / (item_counts["Order Count"].max() - 
                                             item_counts["Order Count"].min())

    return item_counts

In [809]:
item_counts = compute_item_popularity(orders_df)
item_counts = normalize_popularity(item_counts)

menu_df = menu_df.merge(
    item_counts,
    left_on = "Item ID",
    right_on = "Items Ordered ID",
    how = "left"
)

menu_df["Order Count"] = menu_df["Order Count"].fillna(0)
menu_df["Popularity Score"] = menu_df["Popularity Score"].fillna(0)

### Correcting fetaures in $\text{Customers Table}$ based on observed values

In [810]:
customers_df.to_csv(BASE_DIR + "/Data Generation/Data/zomato_customers.csv", index = False)

customers_df.head()

,Customer ID,City,Age,Cuisine Preference,Veg Nonveg Egg Preference,App Usage Frequency,Time Preference,Course Preference
0,100001,Delhi,18,"[0.28, 0.08, 0.32, 0.1, 0.12, 0.08, 0.02]","[0.16, 0.52, 0.32]",high,"[0.54, 0.06, 0.02, 0.14, 0.24]","[0.12, 0.28, 0.13, 0.01, 0.46]"
1,100002,Mumbai,35,"[0.41, 0.12, 0.01, 0.1, 0.14, 0.18, 0.04]","[0.26, 0.55, 0.19]",low,"[0.0, 0.21, 0.33, 0.31, 0.15]","[0.53, 0.18, 0.05, 0.16, 0.08]"
2,100003,Mumbai,38,"[0.08, 0.07, 0.1, 0.19, 0.08, 0.16, 0.32]","[0.48, 0.39, 0.13]",medium,"[0.0, 0.14, 0.4, 0.29, 0.17]","[0.3, 0.2, 0.08, 0.15, 0.27]"
3,100004,Bangalore,25,"[0.07, 0.18, 0.11, 0.1, 0.02, 0.15, 0.37]","[1.0, 0.0, 0.0]",low,"[0.0, 0.12, 0.19, 0.46, 0.23]","[0.36, 0.1, 0.13, 0.04, 0.37]"
4,100005,Delhi,53,"[0.29, 0.0, 0.32, 0.13, 0.02, 0.23, 0.01]","[1.0, 0.0, 0.0]",low,"[0.0, 0.19, 0.05, 0.68, 0.08]","[0.21, 0.18, 0.09, 0.27, 0.25]"

In [811]:
customer_summary = (
    train_df
    .groupby("Customer ID")
    .agg(
        avg_order_value = ("Order Value", "mean"),
        avg_order_items = ("Number of Items", "mean"),
        total_orders = ("Order ID", "nunique")
    )
    .reset_index()
)

customers_df = customers_df.merge(
    customer_summary,
    on = "Customer ID",
    how = "left"
)

In [812]:
customers_df.columns

Index(['Customer ID', 'City', 'Age', 'Cuisine Preference',
       'Veg Nonveg Egg Preference', 'App Usage Frequency', 'Time Preference',
       'Course Preference', 'avg_order_value', 'avg_order_items',
       'total_orders'],
      dtype='object')

In [813]:
train_df.columns

Index(['Order ID', 'Customer ID', 'Order Time', 'Cuisine', 'Items Ordered ID',
       'Items Ordered Name', 'Recommendation Shown ID',
       'Recommendation Shown Name', 'Recommendation Added 1',
       'Recommendation Added 2', 'Recommendation Added 3', 'Order Value',
       'Number of Items'],
      dtype='object')

In [814]:
menu_df.columns

Index(['Item ID', 'Item Name', 'Cuisine', 'Course', 'Veg Type', 'Base Price',
       'Base Multiplier', 'Budget Price', 'Premium Price', 'Items Ordered ID',
       'Order Count', 'Popularity Score'],
      dtype='object')

## Saving all the files

In [815]:
menu_df.to_csv(BASE_DIR + "/Data Generation/Data/zomato_menu.csv", index = False)
customers_df.to_csv(BASE_DIR + "/Data Generation/Data/zomato_customers.csv", index = False)
orders_df.to_csv(BASE_DIR + "/Data Generation/Data/zomato_orders.csv", index = False)
train_df.to_csv(BASE_DIR + "/Data Generation/Data/zomato_train.csv", index = False)
test_df.to_csv(BASE_DIR + "/Data Generation/Data/zomato_test.csv", index = False)